INDUSTRY_ARTISTS = {
    "Bollywood": ["bollywood", "bolywood", "arijit singh", "atif aslam", "shreya ghoshal", "sonu nigam", "kumar sanu", 
                  "lata mangeshkar", "kishore kumar", "neha kakkar", "jubin nautiyal", "armaan malik", 
                  "udit narayan", "alka yagnik", "shaan", "sunidhi chauhan", "kk", "badshah", 
                  "honey singh", "raftaar", "divine", "emiway", "sidhu moose wala", "mohammed rafi", 
                  "asha bhonsle", "mika singh", "vishal dadlani", "shekhar ravjiani", "shankar mahadevan", 
                  "pankaj udhas", "anuradha paudwal", "udit narayan", "kavita krishnamurthy",
                  "vishal-shekhar", "amit trivedi", "himesh reshammiya", "pritam", "a.r. rahman",
                  "salim-sulaiman", "sachin-jigar", "mithoon", "amaal mallik", "tony kakkar",
                  "kanika kapoor", "benny dayal", "mohit chauhan", "papon", "monali thakur",
                  "palak muchhal", "darshan raval", "neeti mohan", "jonita gandhi", "antoni",
                  "kumarr", "irshad kamil", "gulzar", "javed akhtar", "anand bakshi", "rd burman",
                  "sd burman", "bappi lahiri", "mohit chauhan", "shilpa rao", "arijit", "shreya",
                  "armaan", "badshah", "hardy sandhu", "raftaar", "king", "mc stan", "krsna"],
    "Punjabi":   ["punjabi", "panjabi", "diljit dosanjh", "ap dhillon", "sidhu moosewala", "guru randhawa", "hardy sandhu", 
                  "b praak", "ammy virk", "jasmine sandlas", "jassie gill", "babbu maan", 
                  "mankirt aulakh", "sidhu moose wala", "karan aujla", "sharry maan", "gippy grewal",
                  "kulwinder billa", "nimrat khaira", "sunanda sharma", "jass manak", "guri",
                  "sidhu moosewala", "singga", "sidhu", "amrit maan", "bohemia", "gurdas maan",
                  "sharry maan", "pav dharia", "the landers", "prem dhillon", "jordan sandhu",
                  "amrit maan", "mankirt aulakh", "kulwinder billa"],
    "Gujarati":  ["gujarati", "gujrati", "kirtidan gadhvi", "geeta rabari", "aishwarya majmudar", "osman mir", "hemant chauhan", 
                  "kinjal dave", "parthiv gohil", "atul purohit", "falguni pathak", "aditya gadhvi", 
                  "arvind vegda", "jignesh kaviraj", "kajal maheriya", "vijay suvada", "farida mir",
                  "siddharth bhavsar", "dhvanit thaker", "jigardan gadhavi", "bhakti kubavat"],
    "Tollywood": ["tollywood", "telugu", "tamil", "south indian", "anirudh ravichander", "sid sriram", "thaman", "sp balasubrahmanyam", 
                  "devi sri prasad", "sid sriram", "m. m. keeravani", "p. susheela", "s. janaki",
                  "manisharma", "vidyasagar", "harris jayaraj", "g. v. prakash kumar", "d. imman"],
    "Hollywood": ["hollywood", "english", "western", "pop", "rock", "ed sheeran", "taylor swift", "the weeknd", "drake", "eminem", "rihanna", 
                  "beyonce", "coldplay", "adele", "billie eilish", "bruno mars", "dua lipa", 
                  "justin bieber", "ariana grande", "post malone", "shakira", "katy perry", 
                  "maroon 5", "imagine dragons", "linkin park", "lady gaga", "shawn mendes",
                  "camila cabello", "selena gomez", "miley cyrus", "demi lovato", "nick jonas",
                  "charlie puth", "smarshmello", "calvin harris", "david guetta", "alan walker",
                  "rihanna", "sia", "halsey", "rita ora", "bebe rexha", "ava max", "doja cat",
                  "lizzo", "cardi b", "megan thee stallion", "kendrick lamar", "j cole", "kanye west"],
    "Bhojpuri":  ["bhojpuri", "bihari", "khesari lal yadav", "pawan singh", "dinesh lal yadav", "nirahua", "shilpi raj", 
                  "antra singh priyanka", "ritesh pandey", "pramod premi", "arvind akela kallu"],
    "Haryanvi":  ["haryanvi", "haryanvi song", "sapna choudhary", "gulzaar chhaniwala", "amit saini rohtakiya", "md desi kalakaar", 
                  "renuka panwar", "sumit goswami", "khasa ala chahar", "diler kharkiya"],
}


